### PR TITLE
ads: Fix crash with GMS Ads

### PR DESCRIPTION
**Pull request by yiesko**
I'm faster af lmfao

Signed-off-by: Enzo Vieira | YukoSky <daffetyxd@gmail.com>

### CODE REVIEW

**Comment by alissonlauffer** [comment]
ok Enzo

**Comment by alissonlauffer** [comment]
This mod will be rebased anyway, but I'm going to merge this just to get it working.

**Comment by alissonlauffer** [comment]
Lmao, even my CI script is broken.

**Comment by yiesko** [comment]
Kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Pull request merged**
